spring:
  application:
    name: internship

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AppDB
    username: postgres
    password: hagry
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
#  sql:
#    init:
#      mode: always

#spring.datasource:
#  url: jdbc:h2:./internship-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#  username: sa
#  password: sa
server.port: 8081